### PR TITLE
fixes for the custom keyboard

### PR DESCRIPTION
**Pull request by jayrox**
fixes for the custom keyboard where the destination path would start with a '/' such as on OSx and Linux systems. the handler would discard the message thinking it was a command but there wasnt a command waiting to pick it up.

the handler now looks at the current state and if the state is set to FOLDER it will allow the message to pass and be handled by the folder handler.

this also fixes an issue where the folder list `id` was different than the folder's sonarr `id`

### CODE REVIEW

**Comment by jayrox** [comment]
this resolves #9

**Comment by jayrox** [comment]
Awesome, thanks for accepting my PR

**Comment by onedr0p** [comment]
Np, thanks for taking the time to add this and fix the issues!

**Comment by jayrox** [comment]
Np, do you guys have any progress on the authentication stuff? I've been working on it a bit and have something working. Wasn't sure if you have stuff going or if I should proceed with cleaning it up a bit and submitting a PR?

**Comment by onedr0p** [comment]
I haven't started it, maybe @bybeet can give you an answer. 

How does your auth work? Is it the same as discussed here in issue #4 ?

**Comment by jayrox** [comment]
i have a couple commands setup `/getid` would be for the initial config, the admin/owner would run it and get their user id, and add it to a config file. after that a potential user would use `/register` to get added to a pending user list. the admin would then run `/pending` and add the selected user to the allowed users list. i do not have a password configured as being needed. need to add a couple commands still, one to get a list of currently allowed users, one to reject a person from pending and one to revoke access.

**Comment by onedr0p** [comment]
I really like the way we discussed it earlier by having a password, it won't require the admin to do anything other than give the password to the user, and tell them to send it to a /auth command. Any chance we can keep it that way? It doesn't seem far off from what you have and might be a little easier to implement.

**Comment by jayrox** [comment]
yea, let me change my code up a bit to add a password to the main config and remove the need for the owner to mess with the acl.json config

**Comment by jayrox** [comment]
before i change it, im going to post my code to my fork, then i'll look into setting up a password version cause right now my authorized user has checking allowedUsers and owner ids

**Comment by jayrox** [comment]
ok i've updated my fork with the authorization code if you want to check it out.
https://github.com/jayrox/telegram-sonarr-bot

i'll look into setting up a password now instead.

**Comment by onedr0p** [comment]
Interesting! and good work! Please note I just posted a update to `sonarr.js` with a few updates to clearing cache, error handling, and code organization. It seems you left out a few replyWithError functions :)

**Comment by onedr0p** [comment]
Oh and lets move this discussion to #4

**Pull request merged**
